version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 Ecommerce.wsgi:application
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A Ecommerce worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_server
    ports:
      - "6379:6379"



volumes:
  media_volume: