version: '3.8'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build: .
    command: celery -A main worker --loglevel=info  # adjust if celery app in another file
    volumes:
      - .:/app
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  media:
